"""Generates app/src/main/assets/diseases.json - the offline disease knowledge base."""
import json, os

def healthy(crop, tips):
    return dict(type="Healthy", pathogen="None",
                symptoms=["Uniform green colour with no spots, lesions or discolouration",
                          "Normal leaf shape and size", "Vigorous, upright growth"],
                causes=["Good nutrition, watering and field hygiene"],
                organic=["No treatment needed - keep monitoring weekly"],
                chemical=["No chemical treatment required"],
                prevention=tips)

D = {
"Apple___Apple_scab": dict(type="Fungal", pathogen="Venturia inaequalis",
  symptoms=["Olive-green to brown velvety spots on leaves", "Spots turn dark and corky with age", "Leaves may curl, yellow and drop early", "Scabby, cracked lesions on fruit"],
  causes=["Fungus overwinters in fallen infected leaves", "Spores spread by rain splash in spring", "Cool (17-24°C), wet weather with long leaf wetness"],
  organic=["Rake and destroy fallen leaves in autumn", "Spray sulfur or lime-sulfur at bud break", "Apply neem oil or Bacillus subtilis based bio-fungicides"],
  chemical=["Captan 50 WP (2 g/L) at green-tip and petal fall", "Mancozeb 75 WP (2.5 g/L) at 7-10 day intervals", "Myclobutanil or Difenoconazole during infection periods"],
  prevention=["Plant scab-resistant varieties", "Prune to improve air circulation", "Avoid overhead irrigation", "Apply urea to fallen leaves to speed decomposition"]),
"Apple___Black_rot": dict(type="Fungal", pathogen="Botryosphaeria obtusa",
  symptoms=["Purple spots on leaves enlarging to 'frog-eye' lesions with tan centres", "Rotting fruit with concentric brown-black rings", "Sunken cankers on branches", "Mummified fruit stays on tree"],
  causes=["Fungus survives in cankers, dead wood and mummified fruit", "Warm, humid weather (20-30°C)", "Wounds from pruning, hail or insects"],
  organic=["Remove mummified fruit and dead branches", "Prune out cankers 15 cm below visible infection", "Copper-based sprays in early season"],
  chemical=["Captan 50 WP (2 g/L) from petal fall", "Thiophanate-methyl 70 WP (1 g/L)", "Ziram or Mancozeb protective sprays"],
  prevention=["Maintain orchard sanitation", "Avoid tree injuries", "Keep trees vigorous with balanced fertilisation"]),
"Apple___Cedar_apple_rust": dict(type="Fungal", pathogen="Gymnosporangium juniperi-virginianae",
  symptoms=["Bright yellow-orange spots on upper leaf surface", "Small tube-like structures under the spots", "Premature leaf drop", "Deformed fruit with orange lesions"],
  causes=["Fungus alternates between apple and juniper/cedar trees", "Spores blow from galls on cedars in wet spring weather"],
  organic=["Remove nearby juniper/cedar galls", "Sulfur sprays from pink bud to petal fall"],
  chemical=["Myclobutanil (1 ml/L) at pink bud and petal fall", "Mancozeb 75 WP (2.5 g/L) protective sprays"],
  prevention=["Plant rust-resistant apple varieties", "Avoid planting near red cedar/juniper", "Spray during rainy periods in spring"]),
"Apple___healthy": healthy("Apple", ["Prune annually for open canopy", "Apply balanced NPK and calcium", "Clean up fallen leaves and fruit", "Monitor for scab during wet spring weather"]),
"Blueberry___healthy": healthy("Blueberry", ["Keep soil acidic (pH 4.5-5.5)", "Mulch with pine bark or sawdust", "Water regularly - shallow roots dry quickly", "Prune old canes in winter"]),
"Cherry_(including_sour)___Powdery_mildew": dict(type="Fungal", pathogen="Podosphaera clandestina",
  symptoms=["White powdery patches on young leaves", "Leaves curl upward and become distorted", "Infected shoots are stunted", "White fungal growth on fruit near harvest"],
  causes=["Warm days with high humidity and cool nights", "Dense canopies with poor air flow", "Fungus overwinters in buds and bark"],
  organic=["Spray wettable sulfur (2-3 g/L)", "Potassium bicarbonate or milk spray (1:9)", "Neem oil (5 ml/L) every 7 days"],
  chemical=["Hexaconazole 5 EC (1 ml/L)", "Myclobutanil or Trifloxystrobin at first sign", "Rotate fungicide groups to avoid resistance"],
  prevention=["Prune for good air circulation", "Avoid excess nitrogen", "Remove root suckers and water sprouts"]),
"Cherry_(including_sour)___healthy": healthy("Cherry", ["Prune after harvest", "Avoid wetting foliage", "Feed with balanced fertiliser in spring", "Watch for powdery mildew in humid weather"]),
"Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": dict(type="Fungal", pathogen="Cercospora zeae-maydis",
  symptoms=["Rectangular grey to tan lesions between leaf veins", "Lesions 2-5 cm long with sharp parallel edges", "Lesions merge and blight entire leaves", "Lower leaves affected first"],
  causes=["Fungus survives on corn residue", "Warm (25-30°C), humid weather with heavy dews", "Continuous corn with minimum tillage"],
  organic=["Rotate with non-host crops for 1-2 years", "Bury or remove infected residue", "Trichoderma-based bio-fungicide on residue"],
  chemical=["Azoxystrobin + Propiconazole at tasseling", "Pyraclostrobin (1 ml/L)", "Mancozeb 75 WP (2.5 g/L) at early stage"],
  prevention=["Grow resistant hybrids", "Crop rotation", "Avoid dense planting", "Tillage to reduce residue"]),
"Corn_(maize)___Common_rust_": dict(type="Fungal", pathogen="Puccinia sorghi",
  symptoms=["Small cinnamon-brown powdery pustules on both leaf surfaces", "Pustules turn black late in season", "Heavily infected leaves yellow and die"],
  causes=["Wind-blown spores from southern regions", "Cool (16-25°C), humid weather with heavy dew"],
  organic=["Remove volunteer corn plants", "Neem-based sprays early in infection", "Ensure balanced potassium nutrition"],
  chemical=["Mancozeb 75 WP (2.5 g/L) at first pustules", "Propiconazole 25 EC (1 ml/L)", "Azoxystrobin for severe infection"],
  prevention=["Plant resistant hybrids", "Early planting to escape peak spore load", "Scout fields weekly from knee height"]),
"Corn_(maize)___Northern_Leaf_Blight": dict(type="Fungal", pathogen="Exserohilum turcicum",
  symptoms=["Long cigar-shaped grey-green to tan lesions (2.5-15 cm)", "Dark spore masses in lesions in humid weather", "Lesions start on lower leaves and move up"],
  causes=["Fungus overwinters in corn residue", "Moderate temperatures (18-27°C) and prolonged wetness"],
  organic=["Crop rotation with soybean or legumes", "Deep ploughing of residue", "Trichoderma harzianum seed treatment"],
  chemical=["Propiconazole 25 EC (1 ml/L) at first lesions", "Mancozeb (2.5 g/L) sprays at 10-day interval", "Azoxystrobin + Difenoconazole"],
  prevention=["Resistant hybrids with Ht genes", "Balanced fertilisation", "Residue management"]),
"Corn_(maize)___healthy": healthy("Corn", ["Rotate with legumes", "Apply nitrogen in split doses", "Maintain recommended plant spacing", "Scout for rust and blight from V8 stage"]),
"Grape___Black_rot": dict(type="Fungal", pathogen="Guignardia bidwellii",
  symptoms=["Reddish-brown circular leaf spots with dark borders", "Tiny black dots (pycnidia) inside spots", "Berries shrivel into hard black mummies"],
  causes=["Fungus overwinters in mummified berries and canes", "Warm, wet weather during bloom to early berry growth"],
  organic=["Remove all mummies and infected canes", "Copper hydroxide or Bordeaux mixture (1%)", "Improve canopy airflow by leaf removal"],
  chemical=["Mancozeb 75 WP (2 g/L) from bud break", "Myclobutanil or Tebuconazole at bloom", "Captan during berry development"],
  prevention=["Sanitation of vineyard floor", "Train vines for open canopy", "Spray before rains during critical stages"]),
"Grape___Esca_(Black_Measles)": dict(type="Fungal", pathogen="Phaeomoniella / Phaeoacremonium spp. (trunk disease complex)",
  symptoms=["'Tiger-stripe' yellow/red bands between leaf veins", "Small dark spots ('measles') on berries", "Sudden wilting of the whole vine (apoplexy)", "Dark streaks in cross-section of wood"],
  causes=["Wood-infecting fungi entering through pruning wounds", "Stress from drought and heat"],
  organic=["Remove and burn severely affected vines", "Protect pruning wounds with paste or Trichoderma", "Prune in dry weather"],
  chemical=["No curative chemical - protect wounds with fungicide paste (e.g. Tebuconazole)", "Sodium arsenite is banned - avoid"],
  prevention=["Delayed / double pruning", "Avoid large pruning cuts", "Maintain vine vigour with proper irrigation"]),
"Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": dict(type="Fungal", pathogen="Pseudocercospora vitis (Isariopsis clavispora)",
  symptoms=["Irregular dark red-brown spots on leaves", "Spots enlarge and leaves look scorched", "Premature defoliation"],
  causes=["High humidity and warm temperatures", "Spores spread by wind and rain"],
  organic=["Remove and destroy infected leaves", "Bordeaux mixture (1%) or copper oxychloride"],
  chemical=["Mancozeb 75 WP (2 g/L)", "Carbendazim 50 WP (1 g/L)", "Difenoconazole 25 EC (0.5 ml/L)"],
  prevention=["Ensure good canopy ventilation", "Avoid overhead irrigation", "Balanced nutrition"]),
"Grape___healthy": healthy("Grape", ["Train and prune for an open canopy", "Spray protectively before monsoon rains", "Remove mummies after harvest", "Drip irrigation instead of sprinklers"]),
"Orange___Haunglongbing_(Citrus_greening)": dict(type="Bacterial", pathogen="Candidatus Liberibacter asiaticus (spread by Asian citrus psyllid)",
  symptoms=["Blotchy, asymmetric yellow mottling on leaves", "Small, lopsided, bitter fruit that stays green", "Twig dieback and tree decline", "Yellow shoots ('huanglongbing' = yellow dragon)"],
  causes=["Bacterium transmitted by Asian citrus psyllid (Diaphorina citri)", "Infected grafting material"],
  organic=["Remove and destroy infected trees", "Control psyllids with neem oil (5 ml/L)", "Release natural enemies like Tamarixia radiata"],
  chemical=["No cure - manage the psyllid vector", "Imidacloprid 17.8 SL (0.5 ml/L) during new flush", "Thiamethoxam soil drench for young trees"],
  prevention=["Plant certified disease-free nursery stock", "Regular psyllid monitoring", "Nutritional sprays (Zn, Mn) to maintain vigour"]),
"Peach___Bacterial_spot": dict(type="Bacterial", pathogen="Xanthomonas arboricola pv. pruni",
  symptoms=["Small water-soaked spots that turn purple-brown", "Spot centres fall out leaving 'shot holes'", "Pitted, cracked fruit surface", "Heavy leaf drop"],
  causes=["Bacteria overwinter in twig cankers", "Warm, wet, windy weather spreads bacteria", "Sandy soils and stressed trees"],
  organic=["Copper sprays at leaf fall and bud swell", "Prune out cankered twigs", "Improve tree vigour"],
  chemical=["Copper oxychloride (3 g/L) in dormant season", "Oxytetracycline (where permitted) during fruit set", "Streptocycline (0.1 g/L) + copper"],
  prevention=["Plant resistant cultivars", "Windbreaks to reduce leaf injury", "Avoid excess nitrogen"]),
"Peach___healthy": healthy("Peach", ["Prune to an open-centre shape", "Thin fruit for better size", "Apply dormant copper spray", "Remove mummified fruit"]),
"Pepper,_bell___Bacterial_spot": dict(type="Bacterial", pathogen="Xanthomonas campestris pv. vesicatoria",
  symptoms=["Small water-soaked spots turning brown with yellow halo", "Spots merge and leaves drop", "Raised scab-like spots on fruit"],
  causes=["Infected seed and transplants", "Rain splash and overhead irrigation", "Warm (24-30°C), humid weather"],
  organic=["Use hot-water treated seed (50°C for 25 min)", "Remove infected plants", "Copper hydroxide sprays"],
  chemical=["Copper oxychloride (3 g/L) + Streptocycline (0.1 g/L)", "Mancozeb + copper tank mix", "Acibenzolar-S-methyl to boost plant defence"],
  prevention=["Certified disease-free seed", "2-3 year crop rotation", "Drip irrigation", "Avoid working in wet fields"]),
"Pepper,_bell___healthy": healthy("Bell pepper", ["Use drip irrigation and mulch", "Stake plants to keep fruit off soil", "Feed calcium to avoid blossom-end rot", "Rotate away from tomato/potato"]),
"Potato___Early_blight": dict(type="Fungal", pathogen="Alternaria solani",
  symptoms=["Dark brown spots with concentric rings ('target board')", "Yellowing around spots", "Lower, older leaves affected first", "Dark sunken lesions on tubers"],
  causes=["Fungus survives in soil and plant debris", "Warm (24-29°C) weather alternating wet and dry", "Nutrient-stressed or ageing plants"],
  organic=["Remove infected lower leaves", "Spray neem oil or Trichoderma viride", "Copper-based fungicide sprays", "Mulch to prevent soil splash"],
  chemical=["Mancozeb 75 WP (2.5 g/L) at 10-day intervals", "Chlorothalonil 75 WP (2 g/L)", "Azoxystrobin 23 SC (1 ml/L) for severe cases"],
  prevention=["Rotate crops for 2-3 years", "Use certified seed tubers", "Balanced fertilisation, especially nitrogen", "Avoid overhead irrigation"]),
"Potato___Late_blight": dict(type="Oomycete", pathogen="Phytophthora infestans",
  symptoms=["Large dark water-soaked patches on leaves", "White fuzzy growth on leaf undersides in humid weather", "Rapid browning and collapse of foliage", "Reddish-brown dry rot inside tubers"],
  causes=["Cool (10-24°C), very humid weather (>90% RH)", "Infected seed tubers and volunteer plants", "Spores spread rapidly by wind and rain"],
  organic=["Remove and destroy infected plants immediately", "Bordeaux mixture (1%) or copper hydroxide sprays", "Hill soil over tubers to protect them"],
  chemical=["Metalaxyl 8% + Mancozeb 64% WP (2.5 g/L)", "Cymoxanil + Mancozeb (3 g/L)", "Dimethomorph 50 WP (1 g/L)", "Spray every 7 days in blight weather"],
  prevention=["Plant resistant varieties", "Use certified disease-free seed", "Destroy cull piles and volunteers", "Follow blight forecasts and spray preventively"]),
"Potato___healthy": healthy("Potato", ["Use certified seed tubers", "Earth up plants to protect tubers", "Rotate with cereals or legumes", "Spray preventively when blight weather is forecast"]),
"Raspberry___healthy": healthy("Raspberry", ["Remove old fruiting canes after harvest", "Keep rows narrow for airflow", "Mulch to conserve moisture", "Avoid wetting fruit when irrigating"]),
"Soybean___healthy": healthy("Soybean", ["Inoculate seed with Rhizobium", "Rotate with corn or cereals", "Maintain optimal plant population", "Scout for rust and pod borers"]),
"Squash___Powdery_mildew": dict(type="Fungal", pathogen="Podosphaera xanthii / Erysiphe cichoracearum",
  symptoms=["White powdery spots on upper leaf surfaces", "Spots spread to cover whole leaves and stems", "Leaves yellow, dry and die early", "Reduced fruit size and quality"],
  causes=["Warm, dry days and humid nights", "Shaded, crowded plantings", "Spores carried by wind"],
  organic=["Spray potassium bicarbonate (5 g/L)", "Milk spray (1 part milk : 9 water)", "Wettable sulfur (2 g/L) - not above 32°C", "Neem oil (5 ml/L)"],
  chemical=["Hexaconazole 5 EC (1 ml/L)", "Azoxystrobin 23 SC (1 ml/L)", "Myclobutanil (1 ml/L)"],
  prevention=["Plant resistant varieties", "Space plants for good airflow", "Water at the base in the morning", "Remove infected leaves early"]),
"Strawberry___Leaf_scorch": dict(type="Fungal", pathogen="Diplocarpon earlianum",
  symptoms=["Small irregular purple spots on leaves", "Spots merge, leaf edges look burnt / scorched", "Infected leaves dry up and curl"],
  causes=["Fungus survives on infected leaves", "Warm, wet weather and overhead watering"],
  organic=["Remove infected leaves after harvest", "Copper-based sprays", "Renovate beds annually"],
  chemical=["Captan 50 WP (2 g/L)", "Myclobutanil or Thiophanate-methyl"],
  prevention=["Plant resistant cultivars", "Drip irrigation", "Avoid excess nitrogen", "Replant beds every 3-4 years"]),
"Strawberry___healthy": healthy("Strawberry", ["Mulch with straw to keep fruit clean", "Use drip irrigation", "Remove runners as needed", "Renovate beds after harvest"]),
"Tomato___Bacterial_spot": dict(type="Bacterial", pathogen="Xanthomonas spp.",
  symptoms=["Small dark water-soaked spots on leaves", "Spots turn brown with yellow halo", "Raised scabby spots on fruit", "Leaf drop in severe cases"],
  causes=["Infected seed and transplants", "Rain splash and overhead irrigation", "Warm (24-30°C) humid weather"],
  organic=["Remove infected leaves and plants", "Copper hydroxide sprays", "Hot-water seed treatment (50°C, 25 min)"],
  chemical=["Copper oxychloride (3 g/L) + Streptocycline (0.1 g/L)", "Mancozeb + copper tank mix every 7-10 days"],
  prevention=["Disease-free seed and transplants", "Crop rotation 2-3 years", "Drip irrigation", "Disinfect tools and stakes"]),
"Tomato___Early_blight": dict(type="Fungal", pathogen="Alternaria solani",
  symptoms=["Brown spots with concentric rings on older leaves", "Yellow tissue around spots", "Stem lesions near soil line (collar rot)", "Dark leathery spots at fruit stem end"],
  causes=["Fungus in soil and plant debris", "Warm, humid weather with alternate wet/dry periods", "Plant stress and poor nutrition"],
  organic=["Remove lower infected leaves", "Mulch to prevent soil splash", "Neem oil or Bacillus subtilis sprays", "Copper fungicides"],
  chemical=["Mancozeb 75 WP (2.5 g/L)", "Chlorothalonil 75 WP (2 g/L)", "Azoxystrobin or Difenoconazole for severe cases"],
  prevention=["Crop rotation with non-solanaceous crops", "Stake and prune for airflow", "Balanced fertilisation", "Water at base of plants"]),
"Tomato___Late_blight": dict(type="Oomycete", pathogen="Phytophthora infestans",
  symptoms=["Large greasy grey-green to brown patches on leaves", "White mould on leaf undersides in humid weather", "Brown streaks on stems", "Firm brown greasy blotches on fruit"],
  causes=["Cool (10-24°C), wet and humid weather", "Spores spread by wind over long distances", "Infected potato or tomato plants nearby"],
  organic=["Remove and destroy infected plants (do not compost)", "Bordeaux mixture (1%) or copper hydroxide", "Improve spacing and airflow"],
  chemical=["Metalaxyl + Mancozeb (2.5 g/L)", "Cymoxanil + Mancozeb (3 g/L)", "Dimethomorph or Mandipropamid", "Spray every 5-7 days in blight weather"],
  prevention=["Resistant varieties", "Avoid overhead watering", "Keep tomatoes away from potato fields", "Monitor blight forecasts"]),
"Tomato___Leaf_Mold": dict(type="Fungal", pathogen="Passalora fulva (Cladosporium fulvum)",
  symptoms=["Pale green to yellow spots on upper leaf surface", "Olive-green to grey velvety mould underneath", "Leaves curl, wither and drop"],
  causes=["High humidity (>85%) especially in greenhouses", "Poor ventilation", "Temperatures of 22-24°C"],
  organic=["Increase ventilation and reduce humidity", "Remove infected leaves", "Copper-based sprays"],
  chemical=["Chlorothalonil (2 g/L)", "Mancozeb (2.5 g/L)", "Difenoconazole 25 EC (0.5 ml/L)"],
  prevention=["Resistant varieties", "Wider spacing and pruning", "Avoid wetting leaves", "Ventilate greenhouses"]),
"Tomato___Septoria_leaf_spot": dict(type="Fungal", pathogen="Septoria lycopersici",
  symptoms=["Many small circular spots with dark borders and grey centres", "Tiny black dots inside spots", "Lower leaves yellow and drop first"],
  causes=["Fungus survives on plant debris and weeds", "Warm, wet weather and rain splash"],
  organic=["Remove infected lower leaves", "Mulch soil surface", "Copper fungicide or neem oil sprays"],
  chemical=["Chlorothalonil (2 g/L)", "Mancozeb (2.5 g/L) every 7-10 days", "Azoxystrobin for heavy infection"],
  prevention=["Crop rotation", "Remove solanaceous weeds", "Avoid overhead irrigation", "Stake plants"]),
"Tomato___Spider_mites Two-spotted_spider_mite": dict(type="Pest", pathogen="Tetranychus urticae (two-spotted spider mite)",
  symptoms=["Tiny yellow / white speckles (stippling) on leaves", "Fine webbing on leaf undersides", "Leaves turn bronze, dry and drop", "Tiny moving dots visible with a magnifier"],
  causes=["Hot (27-35°C), dry weather", "Dusty conditions", "Overuse of broad-spectrum insecticides killing natural predators"],
  organic=["Spray strong water jets on leaf undersides", "Neem oil (5 ml/L) or insecticidal soap", "Release predatory mites (Phytoseiulus persimilis)"],
  chemical=["Abamectin 1.9 EC (0.5 ml/L)", "Spiromesifen 22.9 SC (1 ml/L)", "Fenpyroximate 5 EC (1 ml/L)", "Rotate miticides to avoid resistance"],
  prevention=["Keep plants well watered", "Control weeds hosting mites", "Avoid excess nitrogen", "Monitor undersides of leaves weekly"]),
"Tomato___Target_Spot": dict(type="Fungal", pathogen="Corynespora cassiicola",
  symptoms=["Brown spots with concentric rings and light centres", "Spots may crack in the centre", "Sunken spots on fruit", "Defoliation from bottom up"],
  causes=["Warm (20-30°C), humid weather", "Long periods of leaf wetness", "Dense canopy"],
  organic=["Prune lower leaves for airflow", "Remove crop debris", "Copper-based sprays"],
  chemical=["Chlorothalonil (2 g/L)", "Azoxystrobin + Difenoconazole", "Boscalid-based fungicides"],
  prevention=["Crop rotation", "Avoid overhead irrigation", "Proper plant spacing"]),
"Tomato___Tomato_Yellow_Leaf_Curl_Virus": dict(type="Viral", pathogen="Tomato yellow leaf curl virus (TYLCV) - spread by whitefly",
  symptoms=["Upward curling and cupping of leaves", "Yellow leaf margins", "Severely stunted plants", "Flower drop and very low fruit set"],
  causes=["Virus transmitted by whitefly (Bemisia tabaci)", "Infected transplants", "Hot, dry seasons with high whitefly populations"],
  organic=["Remove and destroy infected plants", "Yellow sticky traps for whiteflies", "Neem oil (5 ml/L) sprays", "Insect-proof nets in nurseries"],
  chemical=["No cure for the virus - control whiteflies", "Imidacloprid 17.8 SL (0.3 ml/L)", "Thiamethoxam 25 WG (0.3 g/L)", "Spiromesifen for nymphs"],
  prevention=["TYLCV-resistant varieties", "Raise seedlings under insect netting", "Reflective mulches", "Remove weed hosts"]),
"Tomato___Tomato_mosaic_virus": dict(type="Viral", pathogen="Tomato mosaic virus (ToMV)",
  symptoms=["Light and dark green mosaic pattern on leaves", "Leaves distorted, fern-like or puckered", "Stunted growth", "Uneven ripening of fruit"],
  causes=["Very stable virus spread by touch, tools and hands", "Infected seed", "Tobacco products handled near plants"],
  organic=["Remove and burn infected plants", "Wash hands and disinfect tools (10% bleach or milk)", "Do not smoke near plants"],
  chemical=["No chemical cure", "Disinfect seed with trisodium phosphate (10%)"],
  prevention=["Resistant varieties (Tm-2 genes)", "Certified virus-free seed", "Avoid handling wet plants", "Control weeds"]),
"Tomato___healthy": healthy("Tomato", ["Stake and prune for airflow", "Water at the base, ideally by drip", "Mulch to stop soil splash", "Rotate with non-solanaceous crops"]),
}

NAMES = {
 "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Gray Leaf Spot",
 "Corn_(maize)___Common_rust_": "Common Rust",
 "Grape___Esca_(Black_Measles)": "Esca (Black Measles)",
 "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Leaf Blight (Isariopsis)",
 "Orange___Haunglongbing_(Citrus_greening)": "Huanglongbing (Citrus Greening)",
 "Tomato___Spider_mites Two-spotted_spider_mite": "Two-spotted Spider Mite",
 "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Yellow Leaf Curl Virus",
 "Tomato___Tomato_mosaic_virus": "Mosaic Virus",
}
CROPS = {"Cherry_(including_sour)": "Cherry", "Corn_(maize)": "Corn", "Pepper,_bell": "Bell Pepper"}

out = []
for label, v in D.items():
    crop_raw, disease_raw = label.split("___")
    crop = CROPS.get(crop_raw, crop_raw.replace("_", " "))
    name = NAMES.get(label, disease_raw.replace("_", " ").strip().title() if v["type"] != "Healthy" else "Healthy")
    out.append(dict(label=label, crop=crop, name=name, **v))

path = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "assets", "diseases.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1)
print(len(out), "entries ->", path)
